{% set version = "0.4.6" %}

package:
  name: logical-unification
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/l/logical-unification/logical-unification-{{ version }}.tar.gz
  sha256: 908435123f8a106fa4dcf9bf1b75c7beb309fa2bbecf277868af8f1c212650a0
  patches:

build:
  number: 2
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - toolz
    - multipledispatch

test:
  requires:
    - python {{ python_min }}
  imports:
    - unification
  commands:
    - python -c "from importlib.metadata import version; print(version('unification'))"
    - python -c "from importlib.metadata import version; print(version('unification'))" | grep {{ version }}

about:
  home: https://github.com/pythological/unification
  license: BSD-3-Clause
  summary: Logical unification in Python.
  license_file: LICENSE.txt
  dev_url: https://github.com/pythological/unification

extra:
  recipe-maintainers:
    - maresb
    - brandonwillard
